FROM rust:1-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        binutils \
        bash \
        coreutils \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install rustfilt --locked

CMD ["/bin/bash"]
